In [1]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [2]:
c=a[2:4,0:2]
print(c)

[[11 12]
 [16 17]]


In [3]:
d=a.diagonal(offset=1)
print(d)

[ 2  8 14 20]


In [4]:
print(a[0,-2:])

[4 5]
